<!DOCTYPE html><html lang="en-us" >


<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.3.0 for Hugo" />
  

  
  









  




  
  
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Cutive+Mono&family=Lora:wght@400;700&family=Roboto:wght@400;700&display=swap&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cutive+Mono&family=Lora:wght@400;700&family=Roboto:wght@400;700&display=swap&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dina Naji Arch" />

  
  
  
    
  
  <meta name="description" content="library(haven) #read_sav()library(mediation) # mediate() (Tingley, Yamamoto, Hirose, Keele, &amp; Imai, 2014)library(gvlma) # gvlma()library(kableExtra) #kable()library(corrr) #correlate()library(psych) #mediate()library(tidyverse) Mediation in R This exampes comes from a tutorial paper on mediation found here." />

  
  <link rel="alternate" hreflang="en-us" href="https://dinaarch.netlify.app/post/mediation-lab/" />

  
  
  
    <meta name="theme-color" content="#EF525B" />
  

  
  

  

  <link rel="stylesheet" href="/css/vendor-bundle.min.f1ecf783c14edc00c9320c205831ad8e.css" media="print" onload="this.media='all'">

  
  
  
    
    

    
    
    
    
      
      
    
    
    

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
        
      
    

    
    
    
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.min.css" integrity="" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      
        
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.763cd711f24d7b89d45f7edaa68879b4.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/manifest.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_3.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_3.png" />

  <link rel="canonical" href="https://dinaarch.netlify.app/post/mediation-lab/" />

  
  
  
  
  
  
  
  
    
  
  

  
  
    
    
  
  <meta property="twitter:card" content="summary_large_image" />
  
  <meta property="og:site_name" content="Dina Arch" />
  <meta property="og:url" content="https://dinaarch.netlify.app/post/mediation-lab/" />
  <meta property="og:title" content="Mediation Lab | Dina Arch" />
  <meta property="og:description" content="library(haven) #read_sav()library(mediation) # mediate() (Tingley, Yamamoto, Hirose, Keele, &amp; Imai, 2014)library(gvlma) # gvlma()library(kableExtra) #kable()library(corrr) #correlate()library(psych) #mediate()library(tidyverse) Mediation in R This exampes comes from a tutorial paper on mediation found here." /><meta property="og:image" content="https://dinaarch.netlify.app/post/mediation-lab/featured.JPG" />
    <meta property="twitter:image" content="https://dinaarch.netlify.app/post/mediation-lab/featured.JPG" /><meta property="og:locale" content="en-us" />
  
    
      <meta
        property="article:published_time"
        content="2021-12-14T00:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2021-12-14T19:52:21-08:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://dinaarch.netlify.app/post/mediation-lab/"
  },
  "headline": "Mediation Lab",
  
  "image": [
    "https://dinaarch.netlify.app/post/mediation-lab/featured.JPG"
  ],
  
  "datePublished": "2021-12-14T00:00:00Z",
  "dateModified": "2021-12-14T19:52:21-08:00",
  
  "author": {
    "@type": "Person",
    "name": "Dina Naji Arch"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Dina Arch",
    "logo": {
      "@type": "ImageObject",
      "url": "https://dinaarch.netlify.app/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_192x192_fill_lanczos_center_3.png"
    }
  },
  "description": "library(haven) #read_sav()\rlibrary(mediation) # mediate() (Tingley, Yamamoto, Hirose, Keele, \u0026amp; Imai, 2014)\rlibrary(gvlma) # gvlma()\rlibrary(kableExtra) #kable()\rlibrary(corrr) #correlate()\rlibrary(psych) #mediate()\rlibrary(tidyverse)\r Mediation in R This exampes comes from a tutorial paper on mediation found here."
}
</script>

  

  

  

  





  <title>Mediation Lab | Dina Arch</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="3ae766071f7ddbf10e5cbd86b23b9cc9" >

  
  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.2da3b1fa37e894630bf6de39b1b694b3.js"></script>

  


<aside class="search-modal" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#" aria-label="Close"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control"
        aria-label="Search...">
        
      </div>

      
      

      

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Dina Arch</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Dina Arch</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#experience"><span>Experience</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://ucsb.box.com/s/ezcjo8a3b51ke9xxcpd5p6qhes9vfjpr" target="_blank" rel="noopener"><span>CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
      

      
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-label="Display preferences">
          <i class="fas fa-moon" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      
      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    <article class="article">

  




















  
  


<div class="article-container pt-3">
  <h1>Mediation Lab</h1>

  
  <p class="page-subtitle">An example of mediation with multiple mediators for a linear models course</p>
  

  


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Dec 14, 2021
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    12 min read
  </span>
  

  
  
  
  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/labs/">Labs</a></span>
  

</div>

  





</div>


<div class="article-header article-container featured-image-wrapper mt-4 mb-4" style="max-width: 538px; max-height: 258px;">
  <div style="position: relative">
    <img src="/post/mediation-lab/featured.JPG" width="538" height="258" alt="" class="featured-image">
    
  </div>
</div>



  <div class="article-container">

    <div class="article-style">
      <pre><code class="language-r">library(haven) #read_sav()
library(mediation) # mediate() (Tingley, Yamamoto, Hirose, Keele, &amp; Imai, 2014)
library(gvlma) # gvlma()
library(kableExtra) #kable()
library(corrr) #correlate()
library(psych) #mediate()
library(tidyverse)
</code></pre>
<h1 id="mediation-in-r">Mediation in R</h1>
<p>This exampes comes from a tutorial paper on mediation found <a href="https://www.tqmp.org/RegularArticles/vol13-3/p148/p148.pdf" target="_blank" rel="noopener">here</a>.
This is an open source paper that shared the data set used in this example.
The following is code and interpretation are based on this paper.
Note that they use a different package to estimate the model and you will see that our estimates are very close, though not exact.</p>
<p>Kane, L.
&amp; Ashbaugh, A. R.
(2017).
Simple and parallel mediation: A tutorial exploring anxiety sensitivity, sensation seeking, and gender.
<em>The Quantitative Methods for Psychology</em>, 13(3), 148&ndash;165.
<a href="doi:10.20982/tqmp.13.3.p148">doi:10.20982/tqmp.13.3.p148</a></p>
<h2 id="read-in-data">Read in data</h2>
<p>Downloaded from the journal <a href="https://www.tqmp.org/RegularArticles/vol13-3/p148/index.html" target="_blank" rel="noopener">website</a>.</p>
<pre><code class="language-r">tqmp &lt;- read_sav(&quot;p148.sav&quot;)
</code></pre>
<p>+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| Variable Name | Description                                 | Notes                                      |
+===============+=============================================+============================================+
| Gender        | Gender                                      | 0 = female, 1= male                        |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| ASI.TOT       | Anxiety sensitivity index total scale score | higher scores mean more anxiety            |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| ASI.PHY       | ASI-3 physical concerns subscale            | higher values means more concerns          |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| ASI.SOC       | ASI-3 social concerns subscale              | higher values means more concerns          |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| ASI.COG       | ASI-3 cognitive concerns subscale           | higher values means more concerns          |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| SSs           | UPPS-P sensation seeking subscale           | higher values means more sensation seeking |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+
| NUs           | UPPS-P negative urgency subscale            | higher values means more negative urgency  |
+&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;+&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;+</p>
<h2 id="correlation">Correlation</h2>
<p>Just to explore the variables and their relationships we look at a correlation table.</p>
<pre><code class="language-r">#Pretty correlation table:
tab_02 = tqmp%&gt;% 
  correlate() %&gt;%
  shave(upper = TRUE) %&gt;%
  fashion(decimals = 2, na_print = &quot;—&quot;) 
tab_02 %&gt;% 
  kable()
</code></pre>
<table>
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:left;"> Gender </th>
   <th style="text-align:left;"> ASI.TOT </th>
   <th style="text-align:left;"> ASI.PHY </th>
   <th style="text-align:left;"> ASI.SOC </th>
   <th style="text-align:left;"> ASI.COG </th>
   <th style="text-align:left;"> SSs </th>
   <th style="text-align:left;"> NUs </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Gender </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ASI.TOT </td>
   <td style="text-align:left;"> -.12 </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ASI.PHY </td>
   <td style="text-align:left;"> -.17 </td>
   <td style="text-align:left;"> .89 </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ASI.SOC </td>
   <td style="text-align:left;"> -.09 </td>
   <td style="text-align:left;"> .80 </td>
   <td style="text-align:left;"> .54 </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ASI.COG </td>
   <td style="text-align:left;"> -.05 </td>
   <td style="text-align:left;"> .90 </td>
   <td style="text-align:left;"> .75 </td>
   <td style="text-align:left;"> .57 </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SSs </td>
   <td style="text-align:left;"> .19 </td>
   <td style="text-align:left;"> -.23 </td>
   <td style="text-align:left;"> -.27 </td>
   <td style="text-align:left;"> -.17 </td>
   <td style="text-align:left;"> -.14 </td>
   <td style="text-align:left;"> — </td>
   <td style="text-align:left;"> — </td>
  </tr>
  <tr>
   <td style="text-align:left;"> NUs </td>
   <td style="text-align:left;"> .02 </td>
   <td style="text-align:left;"> .38 </td>
   <td style="text-align:left;"> .30 </td>
   <td style="text-align:left;"> .30 </td>
   <td style="text-align:left;"> .39 </td>
   <td style="text-align:left;"> .13 </td>
   <td style="text-align:left;"> — </td>
  </tr>
</tbody>
</table>
<h1 id="simple-mediation-model">Simple Mediation Model</h1>
<p>This example is from the paper directly.</p>
<ul>
<li>
<p>Independent Variable (X): Gender.</p>
</li>
<li>
<p>Dependent Variable (Y): Sensation seeking (SSs)</p>
</li>
<li>
<p>Mediator (M): Anxiety sensitivity (ASI.TOT)</p>
</li>
</ul>
<p>Figure 1.
(from paper)</p>
<p>















<figure  >
  <div class="d-flex justify-content-center">
    <div class="w-100" ><img alt="" srcset="
               /post/mediation-lab/simple_med_hu3f683187e1d086740fe25db8acab2935_19770_fe77fc0ca6ee50546ee4e6be1d1013b1.JPG 400w,
               /post/mediation-lab/simple_med_hu3f683187e1d086740fe25db8acab2935_19770_8cfc66b73f6840a407abe94310b83234.JPG 760w,
               /post/mediation-lab/simple_med_hu3f683187e1d086740fe25db8acab2935_19770_1200x1200_fit_q75_lanczos.JPG 1200w"
               src="/post/mediation-lab/simple_med_hu3f683187e1d086740fe25db8acab2935_19770_fe77fc0ca6ee50546ee4e6be1d1013b1.JPG"
               width="760"
               height="247"
               loading="lazy" data-zoomable /></div>
  </div></figure>
</p>
<h2 id="testing-statistical-assumptions">Testing Statistical Assumptions</h2>
<p>Before we dive into analyzing the mediation model, we first check the statistical assumptions.
Please follow along on page 151 in the tutorial paper to see how they interpreted the assumptions for this mediation model.</p>
<h4 id="linearity-homoscedasticity-normality-of-estimation-error">Linearity, Homoscedasticity, Normality of estimation error</h4>
<p><em>Linearity</em>:&ldquo;To examine these criteria for a simple mediation, you need to plot residuals against predicted values in four regressions: X predicting Y (c), X predicting M (a), M predicting Y (b), and X and M predicting Y (combined linearity of b and c').&rdquo; (pg. 151)</p>
<p><em>Homoscedasticity</em>: &ldquo;To check homoscedasticity, return to the same plot that we created to examine linearity, but this time look for consistency in vertical range across the X axis. In other words, see if the data spreads on the Y axis consistently and equally throughout the plot, resembling a rectangle.&rdquo; (pg. 152)</p>
<p><em>Normality of estimation error</em>: &ldquo;To examine this assumption, we can create a Q-Q plot with the residuals we saved from the regression&rdquo; (pg. 152)</p>
<p>In R, <strong>plot 1</strong> creates a plot of the residuals against the predicted values and <strong>plot 2</strong> creates a Q-Q plot of the residuals.</p>
<pre><code class="language-r"># X predicting Y (path c) 
fit_c &lt;- lm(SSs ~ Gender, data=tqmp) 
plot(fit_c, c(1,2))
</code></pre>
<p><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre><code class="language-r"># X predicting M (path a)
fit_a &lt;- lm(ASI.TOT ~ Gender, data=tqmp) 
plot(fit_a, c(1,2))
</code></pre>
<p><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-3.png" width="672" /><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre><code class="language-r"># M predicting Y (path b)
fit_b &lt;- lm(SSs ~ ASI.TOT, data=tqmp) 
plot(fit_b, c(1,2))
</code></pre>
<p><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-5.png" width="672" /><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-6.png" width="672" /></p>
<pre><code class="language-r"># X and M predicting Y (b and c')
fit_cb &lt;- lm(SSs ~  Gender + ASI.TOT, data=tqmp) 
plot(fit_cb, c(1,2))
</code></pre>
<p><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-7.png" width="672" /><img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-4-8.png" width="672" /></p>
<h2 id="simple-mediation-r-code">Simple Mediation R Code</h2>
<p><strong>Important note!</strong> There are <strong>two</strong> <code>mediate()</code> functions used in this lab.
One comes from the <code>psych</code> package and the other comes from the <code>mediation</code> package.
You must identify the package in the code like shown below to specify which <code>mediate()</code> function you&rsquo;re using.
For simple mediation with one mediator, we use <a href="https://ademos.people.uic.edu/Chapter14.html#24_method_2:_the_mediation_pacakge_method" target="_blank" rel="noopener"><code>mediation::mediate()</code></a>.
For multiple mediators, we use <a href="http://personality-project.org/r/psych/HowTo/mediation.pdf" target="_blank" rel="noopener"><code>psych::mediate()</code></a> shown in the next example.</p>
<p>Recall the steps to test for a mediation effect using one mediator (See slide 15 in lecture):</p>
<pre><code class="language-r"># Model 1: M regressed on X, path a
fit_a &lt;-  lm(ASI.TOT ~ Gender, data=tqmp) 
summary(fit_a)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = ASI.TOT ~ Gender, data = tqmp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -24.135 -11.343  -3.135  10.657  47.449 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   26.135      1.236  21.151   &lt;2e-16 ***
## Gender        -3.584      1.750  -2.048   0.0415 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 15.03 on 293 degrees of freedom
## Multiple R-squared:  0.01411,	Adjusted R-squared:  0.01074 
## F-statistic: 4.192 on 1 and 293 DF,  p-value: 0.0415
</code></pre>
<pre><code class="language-r"># Model 2: Y is regressed on X, path c
fit_c &lt;- lm(SSs ~ Gender, data=tqmp) 
summary(fit_c)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = SSs ~ Gender, data = tqmp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.88379 -0.38379  0.01295  0.44955  1.34628 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.65372    0.04778  55.538  &lt; 2e-16 ***
## Gender       0.23007    0.06769   3.399  0.00077 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5813 on 293 degrees of freedom
## Multiple R-squared:  0.03793,	Adjusted R-squared:  0.03465 
## F-statistic: 11.55 on 1 and 293 DF,  p-value: 0.0007702
</code></pre>
<pre><code class="language-r"># Model 3: Y is regressed on X and M (paths c' and b)
fit_cb &lt;- lm(SSs ~ Gender+ ASI.TOT, data=tqmp) 
summary(fit_cb)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = SSs ~ Gender + ASI.TOT, data = tqmp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.90432 -0.35627  0.01137  0.43682  1.36129 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.864067   0.074417  38.487  &lt; 2e-16 ***
## Gender       0.201224   0.066792   3.013 0.002816 ** 
## ASI.TOT     -0.008049   0.002213  -3.636 0.000327 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5695 on 292 degrees of freedom
## Multiple R-squared:  0.07961,	Adjusted R-squared:  0.07331 
## F-statistic: 12.63 on 2 and 292 DF,  p-value: 5.49e-06
</code></pre>
<pre><code class="language-r"># Path b (not a required step to test for mediation but will be used in the write up)
fit_b &lt;- lm(SSs ~ ASI.TOT, data=tqmp) 
summary(fit_b)
</code></pre>
<pre><code>## 
## Call:
## lm(formula = SSs ~ ASI.TOT, data = tqmp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.80681 -0.41348  0.00638  0.40406  1.32333 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.983622   0.063814  46.755  &lt; 2e-16 ***
## ASI.TOT     -0.008841   0.002228  -3.968 9.11e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5773 on 293 degrees of freedom
## Multiple R-squared:  0.05101,	Adjusted R-squared:  0.04777 
## F-statistic: 15.75 on 1 and 293 DF,  p-value: 9.108e-05
</code></pre>
<h3 id="test-for-indirect-effect">Test for Indirect Effect</h3>
<p>As mentioned in lecture (slide 17), there are multiple ways to estimate the indirect effect and its SE.
The one we will use is the bootstrapped confidence intervals (similar to the tutorial paper as noted on page 153).
In <code>mediation::mediate()</code>, we enter path a and combined path c and b to test the indirect effect using bootstrapping procedures.
In the tutorial paper, they used 10,000 bootstrap samples (pg 153).
This may take a minute to run.
You can cache the results by using <code>{r, cache = TRUE}</code> in the top part of the code chunk so it doesn&rsquo;t need to run every time you knit.
You may decrease the number to 1,000 if you find that&rsquo;s taking too long to run (the results may not be identical to the paper, however).</p>
<p>In the output, we look at the <em>ACME</em> (or Average Causal Mediation Effect) to evaluate the indirect effect of the mediator.
The <em>ADE</em> (or Average Direct Effects) provides the direct effect estimate, and the <em>Total Effect</em> provides the combined indirect and direct effects estimate.
<em>Prop. Mediated</em> is the ratio of these estimates (which we will not be using).</p>
<pre><code class="language-r">fitMed &lt;- mediation::mediate(fit_a, fit_cb, treat=&quot;Gender&quot;, mediator=&quot;ASI.TOT&quot;, boot= TRUE,  boot.ci.type = &quot;perc&quot;, sims = 10000)
summary(fitMed)
</code></pre>
<pre><code>## 
## Causal Mediation Analysis 
## 
## Nonparametric Bootstrap Confidence Intervals with the Percentile Method
## 
##                Estimate 95% CI Lower 95% CI Upper p-value    
## ACME           0.028847     0.000593         0.07  0.0456 *  
## ADE            0.201224     0.069159         0.33  0.0024 ** 
## Total Effect   0.230071     0.099398         0.36  0.0006 ***
## Prop. Mediated 0.125384     0.002647         0.37  0.0462 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Sample Size Used: 295 
## 
## 
## Simulations: 10000
</code></pre>
<p>















<figure  >
  <div class="d-flex justify-content-center">
    <div class="w-100" ><img alt="" srcset="
               /post/mediation-lab/simple_med_w_coef_hue9a2cb9288130c77e246a0d43c3f7fdb_22715_4c3e32fc0f06149197ed82978f4ab76c.jpg 400w,
               /post/mediation-lab/simple_med_w_coef_hue9a2cb9288130c77e246a0d43c3f7fdb_22715_0ad02c9a16263722719bc594ce3a7d4b.jpg 760w,
               /post/mediation-lab/simple_med_w_coef_hue9a2cb9288130c77e246a0d43c3f7fdb_22715_1200x1200_fit_q75_lanczos.jpg 1200w"
               src="/post/mediation-lab/simple_med_w_coef_hue9a2cb9288130c77e246a0d43c3f7fdb_22715_4c3e32fc0f06149197ed82978f4ab76c.jpg"
               width="760"
               height="226"
               loading="lazy" data-zoomable /></div>
  </div></figure>
</p>
<p><em>Note</em>: This figure was taken from the paper.</p>
<h3 id="full-or-partial-mediation">Full or Partial Mediation?</h3>
<p>In this example, the direct effect is still significant when accounting the mediator.
We also see that the direct effect with the mediator (c' = 0.201) is less than the total effect (c = 0.230).
Thus, this is evidence of partial mediation (see Slide 10 in lecture).</p>
<h3 id="sample-write-up">Sample Write-Up</h3>
<p><em>Note</em>: that the estimates from our estimation of the model here is slightly off from what is reported in the manuscript.
They used the <code>PROCESS</code>macro and we use the <code>mediate</code> package.</p>
<p>Results from a simple mediation analysis indicated that gender is indirectly related to sensation seeking through its relationship with anxiety sensitivity.
First, as can be seen in Figure 7, men reported less anxiety sensitivity than women (<em>a</em> = −3.584, <em>p</em> = .042), and lower reported anxiety sensitivity was subsequently related to more sensation seeking (<em>b</em> = −0.008, <em>p</em> =&lt; .001).
A 95% bias-corrected confidence interval based on 10,000 bootstrap samples indicated that the indirect effect (<em>ab</em> = 0.029) was entirely above zero (0.003 to 0.074).
Moreover, men reported greater sensation seeking even after taking into account gender&rsquo;s indirect effect through anxiety sensitivity (<em>c'</em> = 0.201, <em>p</em> = .003).</p>
<h1 id="complex-mediation-with-multiple-mediators">Complex Mediation with Multiple Mediators</h1>
<p>Here, we continue the tutorial paper&rsquo;s example and adding on multiple mediators (three) into the model: Physical, Cognitive, and Social Concerns.</p>
<ul>
<li>
<p>Independent Variable (X): Gender.</p>
</li>
<li>
<p>Dependent Variable (Y): Sensation seeking (SSs)</p>
</li>
<li>
<p>Mediator 1 (M1): Physical Concerns (ASI.PHY)</p>
</li>
<li>
<p>Mediator 2 (M2): Social Concerns (ASI.SOC)</p>
</li>
<li>
<p>Mediator 3 (M3): Cognitive Concerns (ASI.COG)</p>
</li>
</ul>
<p>















<figure  >
  <div class="d-flex justify-content-center">
    <div class="w-100" ><img alt="" srcset="
               /post/mediation-lab/multiple_med_hucc75820830292ef932686c7d57f04614_19178_78b23fbce9c62d8585ed65081be660e3.JPG 400w,
               /post/mediation-lab/multiple_med_hucc75820830292ef932686c7d57f04614_19178_03aa803d804195cc602443b7a3be9f13.JPG 760w,
               /post/mediation-lab/multiple_med_hucc75820830292ef932686c7d57f04614_19178_1200x1200_fit_q75_lanczos.JPG 1200w"
               src="/post/mediation-lab/multiple_med_hucc75820830292ef932686c7d57f04614_19178_78b23fbce9c62d8585ed65081be660e3.JPG"
               width="538"
               height="258"
               loading="lazy" data-zoomable /></div>
  </div></figure>
</p>
<h2 id="testing-statistical-assumptions-1">Testing Statistical Assumptions</h2>
<p>From the paper: &ldquo;We verified the assumptions using the same methods we used for simple mediation, only this time we conducted seven additional regressions (i.e., X [gender] predicting each mediator [the three anxiety sensitivity dimensions]; each mediator predicting Y [sensation seeking]; X and all three mediators predicting Y ; note: we already had regressed Y on X for the simple mediation).&rdquo; (pg 156).</p>
<p>We won&rsquo;t run all seven for this lab, but just note that this is what needs to be done with multiple mediators.</p>
<h2 id="complex-mediation-r-code">Complex Mediation R Code</h2>
<p>We are using the <a href="http://personality-project.org/r/psych/HowTo/mediation.pdf" target="_blank" rel="noopener"><code>psych::mediate()</code></a> function to specify multiple mediators (you can do this in the other package).
This function will go through the steps of mediation as well as provide the tests of indirect effects for each mediator (three).
An important note (again), the results will only show up when you knit the markdown.
We spent <em>many, many</em> hours on this only to find that knitting reveals the specific indirect effect estimates and their significance tests.</p>
<h3 id="test-for-indirect-effect-1">Test for Indirect Effect</h3>
<pre><code class="language-r">fitComplex &lt;- psych::mediate(SSs ~ Gender + (ASI.PHY) + (ASI.SOC)+ (ASI.COG), n.iter = 10000, data = tqmp)
</code></pre>
<img src="https://dinaarch.netlify.app/post/mediation-lab/index_files/figure-html/unnamed-chunk-7-1.png" width="672" />
<pre><code class="language-r">fitComplex
</code></pre>
<pre><code>## 
## Mediation/Moderation Analysis 
## Call: psych::mediate(y = SSs ~ Gender + (ASI.PHY) + (ASI.SOC) + (ASI.COG), 
##     data = tqmp, n.iter = 10000)
## 
## The DV (Y) was  SSs . The IV (X) was  Gender . The mediating variable(s) =  ASI.PHY ASI.SOC ASI.COG .
## 
## Total effect(c) of  Gender  on  SSs  =  0.23   S.E. =  0.07  t  =  3.4  df=  293   with p =  0.00077
## Direct effect (c') of  Gender  on  SSs  removing  ASI.PHY ASI.SOC ASI.COG  =  0.17   S.E. =  0.07  t  =  2.57  df=  290   with p =  0.011
## Indirect effect (ab) of  Gender  on  SSs  through  ASI.PHY ASI.SOC ASI.COG   =  0.06 
## Mean bootstrapped indirect effect =  0.06  with standard error =  0.03  Lower CI =  0.01    Upper CI =  0.12
## R = 0.32 R2 = 0.1   F = 8.2 on 4 and 290 DF   p-value:  2.96e-07 
## 
##  To see the longer output, specify short = FALSE in the print statement or ask for the summary
</code></pre>
<h3 id="sample-write-up-1">Sample Write-Up</h3>
<p>Results from a parallel mediation analysis indicated that gender is indirectly related to sensation seeking through its relationship with the Physical Concerns subscale of anxiety sensitivity.
This dimension pertains to the fear of physiological sensations because of the belief that they may have negative consequences and are life-threatening.
First, as can be seen in Figure 9, men reported less fear of physiological sensations than women (<em>a1</em> = −2.021, <em>p</em> = .004), and lower reported fear of physiological sensations was subsequently related to more sensation seeking (<em>b1</em> = −0.029, <em>p</em> &lt; .001).
A 95% bias-corrected confidence interval based on 10,000 bootstrap samples indicated that the indirect effect through fear of physiological sensations (<em>a1*b1</em> = 0.058), holding all other mediators constant, was entirely above zero (0.017 to 0.132).
In contrast, the indirect effects through both the Social and the Cognitive Concerns subscales of anxiety sensitivity were not different than zero (−0.004 to 0.038 and −0.047 to 0.005, respectively; see Figure 9 (in the paper) for the effects associated with these pathways).
Moreover, men reported greater sensation seeking even when taking into account gender&rsquo;s indirect effect through all three dimensions of anxiety sensitivity (<em>c'</em> = 0.172, <em>p</em> = .011).</p>
<h2 id="next-steps-and-resources">Next steps and resources</h2>
<p>There are extensions of these models.
It is possible to add moderators to this.
This would allow for the mediatoinal relationships to vary by levels of the moderator.
There are resources out there to do this, which we won&rsquo;t cover here.
My hope is that you will have a foundation in moderation and mediation to extend your own knowledge.</p>
<p><a href="https://m-clark.github.io/posts/2019-03-12-mediation-models/" target="_blank" rel="noopener">This</a> resources was a helpful way to learn about mediation and the different package in R.</p>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/r-markdown/">r markdown</a>
  
  <a class="badge badge-light" href="/tag/mediation/">mediation</a>
  
  <a class="badge badge-light" href="/tag/data-analysis/">data analysis</a>
  
</div>



<div class="share-box">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://dinaarch.netlify.app/post/mediation-lab/&amp;text=Mediation%20Lab" target="_blank" rel="noopener" class="share-btn-twitter" aria-label="twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://dinaarch.netlify.app/post/mediation-lab/&amp;t=Mediation%20Lab" target="_blank" rel="noopener" class="share-btn-facebook" aria-label="facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Mediation%20Lab&amp;body=https://dinaarch.netlify.app/post/mediation-lab/" target="_blank" rel="noopener" class="share-btn-email" aria-label="envelope">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://dinaarch.netlify.app/post/mediation-lab/&amp;title=Mediation%20Lab" target="_blank" rel="noopener" class="share-btn-linkedin" aria-label="linkedin-in">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=Mediation%20Lab%20https://dinaarch.netlify.app/post/mediation-lab/" target="_blank" rel="noopener" class="share-btn-whatsapp" aria-label="whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://dinaarch.netlify.app/post/mediation-lab/&amp;title=Mediation%20Lab" target="_blank" rel="noopener" class="share-btn-weibo" aria-label="weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>











  
  



  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <a href="https://dinaarch.netlify.app/"><img class="avatar mr-3 avatar-circle" src="/author/dina-naji-arch/avatar_hu507efff5857c68aef0911fd7748fdc58_1261776_270x270_fill_q75_lanczos_center.jpg" alt="Dina Naji Arch"></a>
    

    <div class="media-body">
      <h5 class="card-title"><a href="https://dinaarch.netlify.app/">Dina Naji Arch</a></h5>
      <h6 class="card-subtitle">Ph.D. Student in Quantitative Methods in the Social Sciences (Education)</h6>
      
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
    <li>
      <a href="mailto:dnaji@ucsb.edu" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/dnajiarch" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/dinanajiarch" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/dina-naji-arch-22649396/" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>
















  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/nonlinear-least-squares-example/">Nonlinear Least Squares Example</a></li>
      
      <li><a href="/post/tips-and-tricks-in-r/">Tips and Tricks in R</a></li>
      
      <li><a href="/post/binary-logistic-regression-lab/">Binary Logistic Regression Lab</a></li>
      
      <li><a href="/post/machine-learning-final-project/">Machine Learning - Final Project</a></li>
      
    </ul>
  </div>
  





  </div>
</article>
  </div>

  <div class="page-footer">
    
    
    <div class="container">
      <footer class="site-footer">

  



  

  

  

  
  






  <p class="powered-by">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a> — the free, <a href="https://github.com/wowchemy/wowchemy-hugo-themes" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>
</footer>

    </div>
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    <script src="/js/vendor-bundle.min.b73dfaac3b6499dc997741748a7c3fe2.js"></script>

    
    
    
      
      
        <script src="https://cdn.jsdelivr.net/gh/desandro/imagesloaded@v4.1.4/imagesloaded.pkgd.min.js" integrity="sha512-S5PZ9GxJZO16tT9r3WJp/Safn31eu8uWrzglMahDT4dsmgqWonRY9grk3j+3tfuPr9WJNsfooOR7Gi7HL5W2jw==" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/gh/metafizzy/isotope@v3.0.6/dist/isotope.pkgd.min.js" integrity="sha512-Zq2BOxyhvnRFXu0+WE6ojpZLOU2jdnqbrM1hmVdGzyeCa1DgM3X5Q4A/Is9xA1IkbUeDd7755dNNI/PzSf2Pew==" crossorigin="anonymous"></script>
      

      
      

      

      
        
        <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js" integrity="sha512-Ypjm0o7jOxAd4hpdoppSEN0TQOC19UtPAqD+4s5AlXmUvbmmS/YMxYqAqarQYyxTnB6/rqip9qcxlNB/3U9Wdg==" crossorigin="anonymous"></script>
        
        
        <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/languages/r.min.js" crossorigin="anonymous"></script>
        
        <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/languages/python.min.js" crossorigin="anonymous"></script>
        
        <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/languages/latex.min.js" crossorigin="anonymous"></script>
        
      

    

    
    
    
      <script src="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.min.js" integrity="" crossorigin="anonymous"></script>
    

    
    

    
    
    
      
      <script id="search-hit-fuse-template" type="text/x-template">
        <div class="search-hit" id="summary-{{key}}">
          <div class="search-hit-content">
            <div class="search-hit-name">
              <a href="{{relpermalink}}">{{title}}</a>
              <div class="article-metadata search-hit-type">{{type}}</div>
              <p class="search-hit-description">{{snippet}}</p>
            </div>
          </div>
        </div>
      </script>
      
        <script src="https://cdn.jsdelivr.net/gh/krisk/Fuse@v3.2.1/dist/fuse.min.js" integrity="sha512-o38bmzBGX+hD3JHWUFCDA09btWaqrNmoJ3RXLlrysA7PP01Kgs4UlE4MhelE1v5dJR3+cxlR4qQlotsW7jKsnw==" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/gh/julmot/mark.js@8.11.1/dist/jquery.mark.min.js" integrity="sha512-mhbv5DqBMgrWL+32MmsDOt/OAvqr/cHimk6B8y/bx/xS88MVkYGPiVv2ixKVrkywF2qHplNRUvFsAHUdxZ3Krg==" crossorigin="anonymous"></script>
      
    

    
    

    
    
    
    

    
    
      
      
      
      
      
      
      
    

    
    
    
    
    
    
    
    
      
      
    
    
    <script src="/en/js/wowchemy.min.7cd6ec29d281a73c92a2958a1584aadc.js"></script>

    
  <script async defer src="https://buttons.github.io/buttons.js"></script>




</body>
</html>
